### ISSUE TITLE
TypeError: Not an object

### ISSUE THREAD

**Issue by jokerxvier** [seishun/node-steam-trade#42]
How can i solve this issue?

connected
encrypt request
handshake complete

undefined:1
function(self) {  var f = this;  return function(arg) {    return f.call(self,
                                                                    ^
TypeError: Not an object
    at Function.serialize (<anonymous>:1:70)
    at SteamClient.handlers.(anonymous function) (/Users/jasonjavier/Documents/node/node_modules/steam/lib/steam_client.js:173:67)
    at SteamClient._netMsgReceived (/Users/jasonjavier/Documents/node/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/Users/jasonjavier/Documents/node/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Connection.Readable.push (_stream_readable.js:130:10)

**Comment by andrewda** [comment]
The same thing happened to me. I simply fixed it by using [Alex7Kom's pull](https://github.com/seishun/node-steam-trade/pull/43).
