### ISSUE TITLE
While using default code, TypeError: Not an object 

### ISSUE THREAD

**Issue by andrewda** [seishun/node-steam-trade#54]
When I attempt to run the default scrapbank.js (with my username and password entered, of course), I get the following error:

```
undefined:1                                                                                                                           
function(self) {  var f = this;  return function(arg) {    return f.call(self,
                                                                    ^
TypeError: Not an object
    at Function.serialize (<anonymous>:1:70)
    at SteamClient.handlers.(anonymous function) (/home/cabox/workspace/node_modules/steam/lib/steam_client.js:173:67)
    at SteamClient._netMsgReceived (/home/cabox/workspace/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.EventEmitter.emit (events.js:95:17)
    at Connection._readPacket (/home/cabox/workspace/node_modules/steam/lib/connection.js:50:8)
    at Connection.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Connection.Readable.push (_stream_readable.js:127:10)
```

**Comment by andrewda** [comment]
Fixed by using Alex7Kom's pull.
