### ISSUE TITLE
Getting Error: Invalid Cookie

### ISSUE THREAD

**Issue by Gacnt** [seishun/node-steam-trade#59]
```
var Steam           = require('steam');
var SteamTrade = require('steam-trade'),
    steamTrade    = new SteamTrade();
var tradeBot        = new Steam.SteamClient();
var pool       = require('mysql').createPool({
    host: '127.0.0.1',
    user: '#####',
    password: '#####'
});

function howDidTheTradeWorkOut(tradeResult) {
    var result;
        switch (tradeResult) {
            case 0:
                result = 'Accepted';
                break;
            case 1:
                result = 'Declined';
                break;
            case 2:
                result = 'Trade Banned Initiator';
                break;
            case 3:
                result = 'Trade Banned Target';
                break;
            case 4:
                result = 'Target Already Trading';
                break;
            case 5:
                result = 'Disabled';
                break;
            case 6:
                result = 'Not Logged In';
                break;
            case 7:
                result = 'Cancel';
                break;
            case 8:
                result = 'Too Soon';
                break;
            case 9:
                result = 'Too Soon Penalty';
                break;
            case 10:
                result = 'Connection Failed';
                break;
            case 11:
                result = 'Already Trading';
                break;
            case 12:
                result = 'Already Has a Trade Request';
                break;
            case 13:
                result = 'No Response';
                break;
            case 14:
                result = 'Cyber Cafe Initiator';
                break;
            case 15:
                result = 'Cyber Cafe Target';
                break;
            case 16:
                result = 'School Lab Initiator or Target';
                break;
            case 18:
                result = 'Initiator is a Blocked Target';
                break;
            case 20:
                result = 'Initiator Needs Verified Email';
                break;
            case 21:
                result = 'Initiator Needs Steam Guard';
                break;
            case 22:
                result = 'Targets Account Cannot Trade';
                break;
            case 23:
                result = 'Initiator Steam Guard Duration';
                break;
            case 24:
                result = 'Initiator Password reset Probation';
                break;
            case 25:
                result = 'Initiator New Device Cooldown';
                break;
            case 50:
                result = 'Ok To Deliver';
                break;
        }
        return result;
        	
    }

function Bot() {
    this.loginDetails = {
        accountName: '####',
        password: '#####'
    };
}

Bot.prototype.activateBot = function() {
    
    // If shaSentryFile for login exists (no steamguard)
    if (require('fs').existsSync('sentry')) {
      this.loginDetails.shaSentryfile = require('fs').readFileSync('sentry');
    }
    
    // Last Recieved Auth Code
    this.loginDetails.authCode = 'G9FCQ';
    
    // Login Bot
    
    tradeBot.logOn(this.loginDetails);
    
    tradeBot.on('error', function(e) {
       console.log(e); 
    });
    
    tradeBot.on('loggedOn', function() { 
        console.log('Logged In');
        tradeBot.setPersonaState(Steam.EPersonaState.Online);
    });

    tradeBot.on('sentry', function(sentry) {
        console.log('Sentry Saved ', sentry);
        require('fs').writeFileSync('sentry', sentry);
    });
    
    tradeBot.on('webSessionID', function(sessionId) {
        console.log('Got a new Web Session ID: ', sessionId); 
        steamTrade.sessionId = sessionId;
        tradeBot.webLogOn(function(cookies) {
            console.log('Retrieving new Cookies. Yum!');
           cookies.forEach(function(cookie) {
               steamTrade.setCookie(cookie);
           });
           console.log(steamTrade.cookie);
        });
    });
};

Bot.prototype.activateTradeHandler = function() {
    console.log('Activated Trade Handler');
    
    tradeBot.on('tradeResult', function(tradeId, result, steamId) {
       console.log(howDidTheTradeWorkOut(result)); 
    });
       
    tradeBot.on('tradeProposed', function(tradeId, otherClientID) {
       console.log('Trade Proposed.');
       tradeBot.respondToTrade(tradeId, true);
    });
    
    tradeBot.on('sessionStart', function(otherClient) {
       var inventory;
       var client = otherClient;
       
       console.log('Trading ' + tradeBot.users[client].playerName);
       
       steamTrade.open(client);
       steamTrade.loadInventory(730, 2, function(inv) {
           inventory = inv;
       });
    });
    
    tradeBot.on('error', function(e) {
        console.log(e);    
    });
    
    steamTrade.on('offerChanged', function(added, item) {
        console.log(item);
        console.log('They ' + (added ? 'added' : 'removed ') + item.name);
    });
    
    steamTrade.on('ready', function() {
      console.log('readying');
      steamTrade.ready(function() {
        console.log('confirming');
        steamTrade.confirm();
      });
    });
    
    steamTrade.on('end', function(status, getItems) {
        if (status === 'complete') {
            getItems(function(items) {
                items.forEach(function(el) {
                   pool.query("SELECT ?? from ?? WHERE ?? = ?", ['id', 'pool', 'active', 1], function(err, rows) {
                       if (err) { return console.log('Failed to find active pool.') }
                       pool.query("UPDATE ?? SET ?? = ?? + ? WHERE ?? = ?", ['pool', 'items_in_pool', 'items_in_pool',
                       items.length, 'id', rows[0].id], function(err, result) {
                           if (err) { return console.log('Failed to insert items into pool.') }
                           console.log('Updated Pool Total Items');
                       });
                       var items = {
                           belongs_to_pool: rows[0].id,
                           belongs_to_id: steamTrade.tradePartnerSteamID(),
                           item_name: el.name
                       };
                       pool.query("INSERT INTO pool_tems SET ?", items, function(err, result) {
                           if (err) { return console.log('Failed to insert items into pool.') }
                            console.log('Added ', el.name);
                       });
                   });
                });
            });
        }
    });
};

Bot.prototype.sendTrade = function(steamId) {
    
    console.log('Sending trade to steamId: ', steamId);
    tradeBot.trade(steamId);

};

module.exports = Bot;

```

And then when I send / accept a trade I get:

```
Error: Invalid cookie
    at /root/Node/**/node_modules/steam-trade/index.js:144:19
    at SteamTrade._onTradeStatusUpdate (/root/Node/**/node_modules/steam-trade/index.js:156:5)
    at Request._callback (/root/Node/**/node_modules/steam-trade/index.js:244:10)
    at Request.self.callback (/root/Node/**/node_modules/steam-trade/node_modules/request/request.js:360:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/root/Node/**/node_modules/steam-trade/node_modules/request/request.js:1202:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/root/Node/**/node_modules/steam-trade/node_modules/request/request.js:1150:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

I'm not sure why the cookies are invalid, when I .log the cookies they show just fine so I'm not sure why they're invalid.

**Comment by Gacnt** [comment]
I had a typo, I had sessionId, instead of sessionID
