### ISSUE TITLE
Getting error when starting the bot

### ISSUE THREAD

**Issue by TMGMilkyx** [seishun/node-steam-trade#62]
When i start the bot it starts then has a bunch of errors.

[root@csgoskinbet бот]# node tradebot.js
connected
encrypt request
handshake complete
Logged in!
/var/www/бот/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'value' of undefined
    at Query._callback (/var/www/бот/tradebot.js:79:80)
    at Query.Sequence.end (/var/www/бот/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/var/www/бот/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/var/www/бот/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/var/www/бот/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/var/www/бот/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/var/www/бот/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/бот/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

**Comment by andrewda** [comment]
It's obviously an error with your MySQL database. Make sure a column with the name `value` doesn't have any null rows.

**Comment by TMGMilkyx** [comment]
It has seemed to make no difference...

**Comment by TMGMilkyx** [comment]
Managed to get it working but now i've got to wait the 7days...

**Comment by andrewda** [comment]
Do you mind sharing what was wrong and how you fixed it in case anyone has this problem in the future?

**Comment by seishun** [comment]
I doubt anyone sane will search for MySQL errors here.

**Comment by andrewda** [comment]
@seishun very good point :laughing:
