### ISSUE TITLE
events.js:85  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by KagamiKuno** [seishun/node-steam-trade#69]
Hello, i get this error when try to run the bot:
root@vps215805:/home/all# node sell.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Disconnected
    at SteamClient._disconnected (/home/all/node_modules/steam/lib/steam_client.js:186:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

**Comment by andrewda** [comment]
*hint:* read the node-steam documentation and look at the examples
