### ISSUE TITLE
bot crashing after a while: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by sonicc1** [seishun/node-steam-trade#70]
hello,
my bots crashing randomly after  1-2 days~ with the same error message. looks like there is an problem with your plugin?

Accepted trade request
/home/nodejs/node/node_modules/steam-trade/index.js:307
  return Object.keys(items).map(function(id) {
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at mergeWithDescriptions (/home/nodejs/node/node_modules/steam-trade/index.js:307:17)
    at SteamTrade.continueFullInventoryRequestIfNecessary (/home/nodejs/node/node_modules/steam-trade/index.js:292:15)
    at Request.self.callback (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:962:12)

**Comment by seishun** [comment]
Check which inventory you're trying to load and whether it actually exists.

**Comment by sonicc1** [comment]
the bots making daily hundred of trades flawless. after 1-2 days they crashing randomly with this error message above. so i think the steam servers are slow / not responding when this error happens. the bots loading the cs go inventory and afterwards the steam inventory.

client.on('tradeStarted', function(steamID) {
	trade.open(steamID.getSteamID64(), function() {
		
		//cs go
		trade.loadInventory(730, 2, function(inv) {
			if (!inv) {
				trade.cancel();
			} else {
				console.log('Found '+inv.length+' CS:GO items in my inventory.');
				
				//add items etc
				
				
				//steam
				trade.loadInventory(753, 6, function(inv2) {
					if (!inv2) {
						trade.cancel();
					} else {
						console.log('Found '+inv2.length+' Steam items in my inventory.');
						
						//add items etc
						
					}
				});
				
			}
		});
	});
});

**Comment by seishun** [comment]
Add the following between lines 290 and 291:

```js
console.log('appid ' + appid + ' contextid ' + contextid);
console.log(body);
```

It'll provide extra info next time it happens.

**Comment by sonicc1** [comment]
ok, it's updated. i will post the logs here when one bot crashes again. so far, thanks for your help.

**Comment by sonicc1** [comment]
the problem wasn't happening for weeks, maybe because i have restarted all bots daily. today it was very often. they crashed today like 4 times.

the steam server is answering with "{ success: false }" and then is the bot crashing.

here is the log:

Accepted trade request
appid 730 contextid 2
{ success: false }
/home/nodejs/node/node_modules/steam-trade/index.js:311
  return Object.keys(items).map(function(id) {
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at mergeWithDescriptions (/home/nodejs/node/node_modules/steam-trade/index.js:311:17)
    at SteamTrade.continueFullInventoryRequestIfNecessary (/home/nodejs/node/node_modules/steam-trade/index.js:296:15)
    at Request.self.callback (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/nodejs/node/node_modules/steam-trade/node_modules/request/request.js:962:12)

**Comment by sonicc1** [comment]
if i have understood your plugin code correctly, then changing line 281 should fix this problem or? maybe you have time to update the plugin on github as well?

`if (error || response.statusCode != 200 || JSON.stringify(body) == '{}') {`

to

`if (error || response.statusCode != 200 || JSON.stringify(body) == '{}' || JSON.stringify(body) == '{ success: false }') {`

thank you

**Comment by seishun** [comment]
Please link to your bot's CS:GO inventory.

**Comment by sonicc1** [comment]
i have currently 6 bots running. all using the same code and they made daily hundred of trades flawless. today is even more horrible then yesterday. i have restarted them alread 9 times(!) and they keep crashing.

when i go with my webbrowser to the cs go inventory it shows me the error "BotXY currently has 0 items in their inventory."

which is wrong, when i refresh it enough, then i see the items. depending on bot up to 900 cs go items. that means clearly, steam servers are broken.

i have tried

`
if (error || response.statusCode != 200 || JSON.stringify(body) == '{}' || JSON.stringify(body) == '{ success: false }') {
`

and

`
if (error || response.statusCode != 200 || JSON.stringify(body) == '{}' || body == '{ success: false }') {
`

but they keep crashing. example: http://steamcommunity.com/profiles/76561198257626862/inventory/

**Comment by seishun** [comment]
>but they keep crashing. example: http://steamcommunity.com/profiles/76561198257626862/inventory/

Is this the bot that crashes? If not, link to the profile of the bot that crashes. Or even better, link the profiles of all your bots.

**Comment by sonicc1** [comment]
yes, this bot is one of them who crashed today and yesterday many times.

**Comment by seishun** [comment]
Next time this happens, try using your browser's developer tools to see what kind of a response it receives when trying to load the inventory.

**Comment by sonicc1** [comment]
alright, i was lucky enough to get a screenshot. its the same error that the bot can see. 

> success:false

screenshot: http://abload.de/img/steamojuyy.png

**Comment by sonicc1** [comment]
looks like i was able to fix this problem.

code:

> 	if (body.success == false) {
		console.log('steam servers are crappy');
	}
	if (error || response.statusCode != 200 || JSON.stringify(body) == '{}' || body.success == false) {
      this.emit('debug', 'loading my inventory: ' + (error || (response.statusCode != 200 ? response.statusCode : '{}')));
      this.loadInventory(appid, contextid, callback);
      return;
    

> }



log:
> Accepted trade request
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
steam servers are crappy
appid 730 contextid 2
{ success: true,
  rgInventory: 
(...)
Accepted trade request
appid 730 contextid 2
{ success: true,
  rgInventory: 
(...)

**Comment by seishun** [comment]
I see, thanks.

I've committed a fix to the [success-false](https://github.com/seishun/node-steam-trade/tree/success-false) branch. Please give it a try. If there are no issues, I'll push it to master.

**Comment by sonicc1** [comment]
maybe i am wrong, but...

> typeof body == 'object'

should be

> typeof body === 'object'

or?

**Comment by sonicc1** [comment]
ok, i have replaced the index.js with the success-false branch. lets see what the next 24 hours brings.

**Comment by sonicc1** [comment]
bots running since 2~ days without crash. so i think you can publish it for everyone.

**Comment by sonicc1** [comment]
bots running since 5~ days without crash. so i think you can publish it for everyone.

**Comment by sonicc1** [comment]
seishun, the success-false branch running fine since 2~ months. so.... maybe push it to the master? :+1:
