### ISSUE TITLE
I have no clue how to use it

### ISSUE THREAD

**Issue by escept** [seishun/node-steam-trade#83]
what are the sessionid, cookies thing? i can't really tell from the docs. Also can you use two factor code for login?

**Comment by seishun** [comment]
Try using https://github.com/Alex7Kom/node-steam-weblogon to get both.

**Comment by escept** [comment]
I'm now getting an error by node-steam-weblogon and i can't really fix it

```
buffer.js:179
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at SteamWebLogOn.webLogOn (C:\Users\escept\node_modules\steam-weblogon\index.js:28:7)
    at SteamUser.<anonymous> (C:\Users\escept\buy.js:25:19)
    at emitTwo (events.js:125:13)
    at SteamUser.emit (events.js:213:7)
    at SteamUser._handlers.(anonymous function) (C:\Users\escept\node_modules\steam-user\components\logon.js:310:9)
    at SteamUser._handleMessage (C:\Users\escept\node_modules\steam-user\components\messages.js:216:29)
    at emitThree (events.js:135:13)
    at CMClient.emit (events.js:216:7)
```

**Comment by seishun** [comment]
Please submit an issue with node-steam-weblogon then.
