### ISSUE TITLE
Invalid cookie

### ISSUE THREAD

**Issue by escept** [seishun/node-steam-trade#84]
Hi, i'm getting invalid cookie errors at steamTrade.open
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Invalid cookie
    at C:\Users\escept\node_modules\steam-trade\index.js:144:19
    at SteamTrade._onTradeStatusUpdate (C:\Users\escept\node_modules\steam-trade\index.js:156:5)
    at Request._callback (C:\Users\escept\node_modules\steam-trade\index.js:244:10)
    at Request.self.callback (C:\Users\escept\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\escept\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\escept\node_modules\request\request.js:1091:12)
```

```
client.on('tradeStarted', function(steamID) {
	client.webLogOn(function(webSessionID, cookies){
    });
	steamTrade.open(steamID.getSteamID64()); 
	steamTrade.chatMsg("test")
});
```

```
client.on('webSession', function(sessionID, cookies) {
	steamTrade.setCookie(cookies[0])
	steamTrade.setCookie(cookies[1])
	console.log(cookies[0])
	console.log(cookies[1]);
});
```

**Comment by seishun** [comment]
You didn't set the sessionID property.

>Before you use it, make sure it has the necessary session information. See sessionID and setCookie.

**Comment by escept** [comment]
How do I set the sessionid though? I'm pretty new to node.

**Comment by seishun** [comment]
`steamTrade.sessionID = sessionID`

**Comment by escept** [comment]
thanks!

**Comment by escept** [comment]
oh and one last question, what does the additem require? id or what?

**Comment by seishun** [comment]
An item from the array provided by `loadInventory`.

**Comment by escept** [comment]
could you explain that async map at adding multiple items? i saw the function though i don't know how to implement it
